name: dreamt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib-base
  - ipykernel
  - ipython
  - scikit-datasets
  - scikit-fda
  - pandas
  - sympy
  - tqdm
  - findiff
  - fdasrsf
  - dcor
  - cython
  - gmpy2
  - mpmath
  - patsy
  - xarray
  - colorama
  - joblib
  - decorator
  - typing-extensions
  - traitlets
  - importlib-metadata
  - jupyter_client
  - jupyter_core
  - tornado
  - pygments
  - parso
  - jedi
  - prompt-toolkit
  - pyzmq
  - nest-asyncio
  - pexpect
  - six
  - typing_extensions
  - packaging
  - pyparsing
  - unicodedata2
  - comm
  - matplotlib-inline
  - threadpoolctl
  - multimethod
  - lazy_loader
  - exceptiongroup
  - executing
  - asttokens
  - pure_eval
  - backports
  - backports.functools_lru_cache
  - stack_data
  - wheel
  - setuptools
  - readline
  - tk
  # These packages are required but were not initially added to the list; 
  # possibly because we removed Linux packages
  - pip:
      - seaborn
      - torch
      - lightgbm
      - gpboost
      - hyperopt
      - imbalanced-learn
      - ipywidgets
